### ISSUE TITLE
Panic when using mutate

### ISSUE THREAD

**Issue by alexwhitman** [AgilData/mysql-proxy-rs#17]
I'm completely new to rust so this could well be user error.

I've been playing around with the proxy example to mutate `CREATE TABLE` queries so that they will always have `ROW_FORMAT=DYNAMIC` appended if a row format is not already defined.  The modified proxy example has been changed to

``` rust
if sql.to_lowercase().starts_with("create table ") && ! sql.to_lowercase().contains(" row_format") {
    let new_sql = sql + " ROW_FORMAT=DYNAMIC";

    let mut payload: Vec<u8> = vec![];
    payload.extend_from_slice(&p.bytes[0..5]);
    payload.extend_from_slice(new_sql.as_bytes());

    let new_packet = Packet { bytes: payload };

    print_packet_bytes(&new_packet.bytes);

    Action::Mutate(new_packet)
}
```

When running a create statement such as `CREATE TABLE test1 (id int);` the printed bytes are correct (i.e. containing the extra appended `ROW_FORMAT=DYNAMIC`) but the application crashes with

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 107, message: "Transport endpoint is not connected" } }', ../src/libcore/result.rs:799
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/debug/examples/proxy` (exit code: 101)
```

I can provide a back trace if required.  Additionally the table does get created but without the `ROW_FORMAT` being set.

Is this something in the application or am I doing something wrong?

**Comment by andygrove** [comment]
Hi Alex,

Sorry for the delay in responding. 

I see one bug - when creating the new packet you are copying the first 5 bytes from the original packet, so you are copying the packet length (first three bytes) rather than modifying the packet length to be correct for the length of the new SQL string.

I would guess that this is somehow causing a protocol error that then causes MySQL to close the connection.

Here's a snippet of code for populating the first three bytes with the correct packet length. This is from a different project so may need a little tweaking.

``` rust
 let l = self.payload.len() - 4;
        let mut header : Vec<u8> = Vec::with_capacity(4);
        // write the payload length to the header
        header.write_u32::<LittleEndian>(l as u32).unwrap();
        // length is a 3-byte little-endian integer, so the fourth byte must always be zero
        assert!(0x00 == header[3]);
        // copy the header into the payload
        self.payload[0] = header[0];
        self.payload[1] = header[1];
        self.payload[2] = header[2];
```

This requires the `byteorder` crate. 

Hope that helps.

Andy.

**Comment by alexwhitman** [comment]
Thanks Andy, that fixed it and the library is working really well.
